services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ms-social-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ms-social-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ms-social-network

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api-gateway
    networks:
      - ms-social-network

  api-gateway:
    build: ./ApiGateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    networks:
      - ms-social-network

  user-service:
    build: ./UserService
    ports:
      - "8081:8080"
    depends_on:
      - db
      - rabbitmq
      - kafka
    networks:
      - ms-social-network
    environment:
      KAFKA_BROKER: kafka:9092

  post-service:
    build: ./PostService
    ports:
      - "8082:8080"
    depends_on:
      - db
      - rabbitmq
      - kafka
    networks:
      - ms-social-network

  notification-service:
    build: ./NotificationService
    ports:
      - "8083:8080"
    depends_on:
      - db
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      SMTP_USERNAME:
      SMTP_PASSWORD:
    networks:
      - ms-social-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ms-social-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - ms-social-network

  user-profile-mfe:
    build:
      context: .
      dockerfile: frontend/packages/user-profile/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - ms-social-network

  dashboard-mfe:
    build:
      context: .
      dockerfile: frontend/packages/dashboard/Dockerfile
    ports:
      - "3002:3002"
    networks:
      - ms-social-network

  host-app:
    build:
      context: .
      dockerfile: frontend/packages/host/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-profile-mfe
      - dashboard-mfe
    networks:
      - ms-social-network

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    networks:
      - ms-social-network


networks:
  ms-social-network:
    driver: bridge


volumes:
  db-data: